### PR TITLE
Add benchmark routing

### LINKED ISSUE #286: Add osu! benchmark submission endpoint
@Digitalfear117 has made a name for himself in the discord due to his modded osu! client, which includes a feature from b20121003shine.test - The Benchmark. His idea was to create a separate leaderboard using the data from the results screen.

### PR DESCRIPTION
**Pull request by how-to-do-frontend**
the riskiest one yet

Closes #286

### CODE REVIEW

**Comment by Lekuruu** [comment]
@how-to-do-frontend What would be some good validation for raw score and framerate?

**Comment by Zordon1337** [comment]
> @how-to-do-frontend What would be some good validation for raw score and framerate?

maybe ask Digital for some encryption and score checksum, but i think it won't be enough

**Comment by how-to-do-frontend** [comment]
i mean faking this is pretty easy, but so is score sub in the same way, just a bit more encryption

**Comment by Lekuruu** [comment]
Score checksum & encryption would be kind of pointless I think

**Comment by Zordon1337** [comment]
> i mean faking this is pretty easy, but so is score sub in the same way, just a bit more encryption

obfuscate client, choose some secret key for obfuscation in aes 256 and hide it somehow :trollface:

**Comment by Lekuruu** [comment]
Dude, titanic is open-source

**Comment by Zordon1337** [comment]
> Dude, titanic is open-source

you've took it too seriously :trollface:

**Comment by Lekuruu** [comment]
yes i did

**Review by Lekuruu — APPROVED** [review]
Okay, this should be fine now

**Pull request merged**
